name:                danac

dependencies:
- base

library:
  source-dirs: src
  exposed-modules:
  - Danac.Ast
  - Danac.Util.Annotation
  - Danac.Util.SourceSpan
  - Danac.Util.Derive
  - Danac.Util.Helpers
  - Danac.Parser
  - Danac.Renamer
  - Danac.TypeChecker
  - Danac.Codegen
  dependencies:
  - megaparsec
  - parser-combinators
  - text
  - containers
  - validation
  - mtl
  - compdata
  - template-haskell
  - llvm-hs-pure
  - bytestring

executables:
  danac-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text
    - danac
    - megaparsec
    - pretty-simple
    - mtl
    - validation
    - compdata
    - bytestring
    - llvm-hs
    - optparse-applicative
