name:                danac

dependencies:
- base

library:
  source-dirs: src
  exposed-modules:
  - Danac.Ast
  - Danac.Util.Annotation
  - Danac.Util.SourceSpan
  - Danac.Util.Derive
  - Danac.Parser
    #- Danac.Ast
    #- Danac.Parser.Core
    #- Danac.Renamer.Core
  dependencies:
  - megaparsec
  - parser-combinators
  - text
  - containers
  - validation-selective
  - mtl
  - compdata
  - template-haskell

executables:
  danac-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - danac
    - mtl
    - compdata
    - validation-selective
  hello_world-exe:
    source-dirs:       acceptance-tests/hello_world
    main:              Main.hs 
    dependencies:
    - text
    - danac
    - megaparsec
    - pretty-simple
    - mtl
    - validation-selective
  bubblesort-exe:
    source-dirs:       acceptance-tests/bubble_sort
    main:              Main.hs 
    dependencies:
    - text
    - danac
    - megaparsec
    - pretty-simple
    - mtl
    - validation-selective
